#application: dankbot-dankbot
#version: 1
runtime: python37
api_version: 1

handlers:
-   url: /set_webhook
    login: admin
    script: main.app

-   url: .*
    script: main.app

#libraries:
#-   name: webapp2
#    version: "2.5.2"
#-   name: PIL
#    version: latest
